name: ruru labo
favicon: null
layout_spectrum: 0.9906231581699103
typography_spectrum: 0.6317979821469635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9778141244314611
  lightness: 0.7662726182024926
  saturation: 0.24886542675085366
  rhythmicContrast: 0.5518760038539767
purpose: []
